### ISSUE TITLE
crash with chickens-4.2

### ISSUE THREAD

**Issue by SDUBZ** [setycz/ChickensMod#58] opened 2017-01-03 16:14 UTC
#### Issue Description:
crashes on load up after updating

#### Steps to reproduce (important):

1. update chickens to 4.2 and more chickens to 1.0.8
2. launch game and crash
3. 
...

#### What happens:
it crashes on launch

#### What you expected to happen:
it to launch after update

____
#### Affected Versions (Do *not* use "latest"):

- Chickens: 4.2
- Minecraft: 1.10.2
- Forge: 1.10.2-2202

crash report:
[crash-2017-01-04_03.03.36-client.txt](https://github.com/setycz/ChickensMod/files/682621/crash-2017-01-04_03.03.36-client.txt)

**Comment by GenDeathrow** [comment] 2017-01-03 16:18
Some chicken names overlapped and I am changing them on my side in more chickens. This isnt really a chickens issuers a "more chickens" issue. Please close this and you can post under more chickens. The change log tells ya its broken for the time being. Update is scheduled for today.

**Comment by setycz** [comment] 2017-01-03 16:20
@GenDeathrow it says
> Caught exception from More Chickens (morechickens)
Caused by: java.lang.NoSuchMethodError: com.setycz.chickens.ChickensRegistryItem.setParents

I may have changed that method to return `this`. I can create a hotfix but if you have other problems I can leave up to you, what do you think?

**Comment by SDUBZ** [comment] 2017-01-03 16:25
ok thanks guys i was gonna post on your end aswell as it mentioned both @GenDeathrow

**Comment by setycz** [comment] 2017-01-03 16:26
@GenDeathrow Yeah, it's caused by the change in the API. I will create a HOTFIX. Sorry for inconvenience, I'll test it with More Chickens the next time.

**Comment by SDUBZ** [comment] 2017-01-03 16:27
@setycz luckily i tested the compat for you lol

**Comment by setycz** [comment] 2017-01-03 16:33
I have just uploaded a new release 4.2.1. Please let me know if you encounter any problems and thank you for the report!

**Comment by SDUBZ** [comment] 2017-01-03 16:35
hey no problem :D @setycz

**Comment by SDUBZ** [comment] 2017-01-03 16:46
@setycz its not fixed yet mate 
chickens 4.2.1
crash:
[crash-2017-01-04_03.44.11-client.txt](https://github.com/setycz/ChickensMod/files/682737/crash-2017-01-04_03.44.11-client.txt)

**Comment by setycz** [comment] 2017-01-03 17:04
Please send me your config files: chickens.cfg and morechickens.cfg . have you done any changes in them? Try to delete them and let the game generate fresh configs.

**Comment by setycz** [comment] 2017-01-03 17:07
Which version of MoreChickens are you using?

---
Update: it's 1.0.8, I see it in the log file :D

**Comment by setycz** [comment] 2017-01-03 17:27
@GenDeathrow I think that 'silverchicken' may cause the issue. Do you think you can rename it? It shouldn't cause any problems because ID is stored in the files and not entity name, correct?

**Comment by P3rf3ctXZer0** [comment] 2017-01-03 17:39
@GenDeathrow how quickly can the fix come out? I have players pissed my server is down.

**Comment by SDUBZ** [comment] 2017-01-03 17:41
@setycz oh sorry here ya go the configs


[config.zip](https://github.com/setycz/ChickensMod/files/682881/config.zip)

**Comment by SDUBZ** [comment] 2017-01-03 17:42
@P3rf3ctXZer0 why not roll back 1 version for now?

**Comment by setycz** [comment] 2017-01-03 17:55
@P3rf3ctXZer0 and @SDUBZ  I have create a hotfix which should fix the issue with silver chicken. Can somebody check the new release 4.2.2 and confirm that it was solved?

@GenDeathrow We should have some time to fix the conflict in a more clean way :D

**Comment by SDUBZ** [comment] 2017-01-03 17:56
@setycz will test in 2 secs
is it posted to curseforge yet?

**Comment by setycz** [comment] 2017-01-03 17:57
curse is still doing review, should be in a minute ;]

**Comment by SDUBZ** [comment] 2017-01-03 17:58
@setycz quite fun having to wait isnt it,i do modpacks myself during christmas it took like 8 hours to approve

**Comment by setycz** [comment] 2017-01-03 18:02
@SDUBZ you may have to delete chickens.cfg or remove silverchicken entry. And it's approved! 🎆

**Comment by SDUBZ** [comment] 2017-01-03 18:05
@setycz ok will do man ,so far no crash

**Comment by SDUBZ** [comment] 2017-01-03 18:07
okay chickens-4.2.2.jar worked \o/

thank you very much 👍

**Comment by setycz** [comment] 2017-01-03 18:13
huray 🎆 🎆 🎆  Thank you @SDUBZ  very much for your great help!

**Closed as completed by setycz** 2017-01-03 18:13 UTC
Labels: bug

**Comment by SDUBZ** [comment] 2017-01-03 18:16
@setycz anytime man :D

**Comment by P3rf3ctXZer0** [comment] 2017-01-03 18:21
I just noticed and you beat to the punch @SDUBZ

**Comment by GenDeathrow** [comment] 2017-01-03 18:29
Sorry guys im at work when I responded. It wouldn't be for quite a few hours before I could update.

 @setycz I knew it felt with the silver chicken from base metals too be honest I was thinking or renaming them all to include ore in the name.

I had Found it last night but didnt have time to fix it my side. Ill update my dev version again to make sure we are still compatable with my next update.

@P3rf3ctXZer0 and @SDUBZ  sorry for the trouble.
